In [112]:
import numpy as np
from pyinform.dist import Dist

from pyinform.shannon import entropy, mutual_info, conditional_entropy

from scipy.stats import entropy as sp_entropy
from sklearn.metrics import mutual_info_score

import sys
eps = sys.float_info.epsilon

### ENTROPY

In [2]:
obs = [0,0,0,5]
d = Dist(max(obs)+1)
for event in obs:
    d.tick(event)

In [3]:
print(f'Entropy:{entropy(d):.3f} bits')

Entropy:0.811 bits


In [4]:
for b in np.arange(2,12,2):
    print(f'Entropy:{entropy(d, b=b):.3f} b={b}')

Entropy:0.811 b=2
Entropy:0.406 b=4
Entropy:0.314 b=6
Entropy:0.270 b=8
Entropy:0.244 b=10


### MUTUAL INFORMATION

In [5]:
np.random.seed(2019)
obs = np.random.randint(0, 10, 100)
np.unique(obs)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
p_xy = Dist(100) # NUMBER OF STATES
p_x  = Dist(10)
p_y  = Dist(10)

symbols = []

for x in obs[:-1]:
    for y in obs[1:]:
        #print(x,y)
        p_x.tick(x)
        p_y.tick(y)
        p_xy.tick(10*x + y)
        symbols.append(10*x + y)

print(mutual_info(p_xy, p_x, p_y))
print(mutual_info(p_xy, p_x, p_y, b=10))

1.3322676295501878e-15
4.440892098500626e-16


In [7]:
print(f'Symbols: {len(np.unique(obs))} -> {np.unique(obs)} \nN observations: {p_x.counts()} \nHistogram: {len(list(p_x))} -> {list(p_x)}')

Symbols: 10 -> [0 1 2 3 4 5 6 7 8 9] 
N observations: 9801 
Histogram: 10 -> [1485, 1188, 990, 693, 693, 792, 891, 1188, 1386, 495]


In [8]:
print(f'Symbols: {len(np.unique(obs))} -> {np.unique(obs)} \nN observations: {p_y.counts()} \nHistogram: {len(list(p_y))} -> {list(p_y)}')

Symbols: 10 -> [0 1 2 3 4 5 6 7 8 9] 
N observations: 9801 
Histogram: 10 -> [1485, 1188, 1089, 693, 693, 792, 891, 1188, 1287, 495]


In [9]:
print(f'Symbols: {len(np.unique(symbols))} -> {np.unique(symbols)} \nN observations: {p_xy.counts()} \nHistogram: {len(list(p_xy))} -> {list(p_xy)}')

Symbols: 100 -> [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99] 
N observations: 9801 
Histogram: 100 -> [225, 180, 165, 105, 105, 120, 135, 180, 195, 75, 180, 144, 132, 84, 84, 96, 108, 144, 156, 60, 150, 120, 110, 70, 70, 80, 90, 120, 130, 50, 105, 84, 77, 49, 49, 56, 63, 84, 91, 35, 105, 84, 77, 49, 49, 56, 63, 84, 91, 35, 120, 96, 88, 56, 56, 64, 72, 96, 104, 40, 135, 108, 99, 63, 63, 72, 81, 108, 117, 45, 180, 144, 132, 84, 84, 96, 108, 144, 156, 60, 210, 168, 154, 98, 98, 112, 126, 168, 182, 70, 75, 60, 55, 35, 35, 40, 45, 60, 65, 25]


In [11]:
d_event = {}
s=0
for event in np.unique(symbols):
    s += p_xy[event]
    d_event[event] = p_xy[event]
    print(f'Multiplicity({event}): {p_xy[event]} - {s}')

Multiplicity(0): 225 - 225
Multiplicity(1): 180 - 405
Multiplicity(2): 165 - 570
Multiplicity(3): 105 - 675
Multiplicity(4): 105 - 780
Multiplicity(5): 120 - 900
Multiplicity(6): 135 - 1035
Multiplicity(7): 180 - 1215
Multiplicity(8): 195 - 1410
Multiplicity(9): 75 - 1485
Multiplicity(10): 180 - 1665
Multiplicity(11): 144 - 1809
Multiplicity(12): 132 - 1941
Multiplicity(13): 84 - 2025
Multiplicity(14): 84 - 2109
Multiplicity(15): 96 - 2205
Multiplicity(16): 108 - 2313
Multiplicity(17): 144 - 2457
Multiplicity(18): 156 - 2613
Multiplicity(19): 60 - 2673
Multiplicity(20): 150 - 2823
Multiplicity(21): 120 - 2943
Multiplicity(22): 110 - 3053
Multiplicity(23): 70 - 3123
Multiplicity(24): 70 - 3193
Multiplicity(25): 80 - 3273
Multiplicity(26): 90 - 3363
Multiplicity(27): 120 - 3483
Multiplicity(28): 130 - 3613
Multiplicity(29): 50 - 3663
Multiplicity(30): 105 - 3768
Multiplicity(31): 84 - 3852
Multiplicity(32): 77 - 3929
Multiplicity(33): 49 - 3978
Multiplicity(34): 49 - 4027
Multiplicity(35

In [12]:
m = np.zeros((10,10))
m2 = np.zeros((10,10))
for x in range(10):
    for y in range(10):
        m[x][y] = 10*x + y
        m2[x][y] = d_event[10*x + y]

In [13]:
m

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
       [50., 51., 52., 53., 54., 55., 56., 57., 58., 59.],
       [60., 61., 62., 63., 64., 65., 66., 67., 68., 69.],
       [70., 71., 72., 73., 74., 75., 76., 77., 78., 79.],
       [80., 81., 82., 83., 84., 85., 86., 87., 88., 89.],
       [90., 91., 92., 93., 94., 95., 96., 97., 98., 99.]])

In [14]:
m2

array([[225., 180., 165., 105., 105., 120., 135., 180., 195.,  75.],
       [180., 144., 132.,  84.,  84.,  96., 108., 144., 156.,  60.],
       [150., 120., 110.,  70.,  70.,  80.,  90., 120., 130.,  50.],
       [105.,  84.,  77.,  49.,  49.,  56.,  63.,  84.,  91.,  35.],
       [105.,  84.,  77.,  49.,  49.,  56.,  63.,  84.,  91.,  35.],
       [120.,  96.,  88.,  56.,  56.,  64.,  72.,  96., 104.,  40.],
       [135., 108.,  99.,  63.,  63.,  72.,  81., 108., 117.,  45.],
       [180., 144., 132.,  84.,  84.,  96., 108., 144., 156.,  60.],
       [210., 168., 154.,  98.,  98., 112., 126., 168., 182.,  70.],
       [ 75.,  60.,  55.,  35.,  35.,  40.,  45.,  60.,  65.,  25.]])

In [15]:
joint = m2/np.sum(m2)
np.round(joint,2)

array([[0.02, 0.02, 0.02, 0.01, 0.01, 0.01, 0.01, 0.02, 0.02, 0.01],
       [0.02, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.02, 0.01],
       [0.02, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01],
       [0.01, 0.01, 0.01, 0.  , 0.  , 0.01, 0.01, 0.01, 0.01, 0.  ],
       [0.01, 0.01, 0.01, 0.  , 0.  , 0.01, 0.01, 0.01, 0.01, 0.  ],
       [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.  ],
       [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.  ],
       [0.02, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.02, 0.01],
       [0.02, 0.02, 0.02, 0.01, 0.01, 0.01, 0.01, 0.02, 0.02, 0.01],
       [0.01, 0.01, 0.01, 0.  , 0.  , 0.  , 0.  , 0.01, 0.01, 0.  ]])

### Distribution

In [69]:
pX, pY = joint.sum(1), joint.sum(0)
pX

array([0.15151515, 0.12121212, 0.1010101 , 0.07070707, 0.07070707,
       0.08080808, 0.09090909, 0.12121212, 0.14141414, 0.05050505])

In [70]:
p_x.dump()

array([0.15151515, 0.12121212, 0.1010101 , 0.07070707, 0.07070707,
       0.08080808, 0.09090909, 0.12121212, 0.14141414, 0.05050505])

### Entropy

In [74]:
print(f'Entropy:{entropy(p_x):.4f} bits')

Entropy:3.2495 bits


In [90]:
hX = sp_entropy(pX, base=2)
hX

3.249491537197391

### Mutual Information

In [91]:
print(mutual_info(p_xy, p_x, p_y, b=np.e))
print(mutual_info(p_xy, p_x, p_y, b=2))
print(mutual_info(p_xy, p_x, p_y, b=10))

4.440892098500626e-16
1.3322676295501878e-15
4.440892098500626e-16


In [104]:
pX_Y = joint/pY
hX_Y =  np.sum(pY * np.log2(np.e) * np.apply_along_axis(sp_entropy, 0, pX_Y))
print(f'H(X|Y): {hX_Y} bits')
miXY = hX - hX_Y
print(f'I(X,Y): {miXY} bits')

H(X|Y): 3.2494915371973905 bits
I(X,Y): 4.440892098500626e-16 bits


In [105]:
hX_Y = np.sum(sp_entropy(pX_Y, base=2) * pY)
print(f'H(X|Y): {hX_Y} bits')
miXY = hX - hX_Y
print(f'I(X,Y): {miXY} bits')

H(X|Y): 3.2494915371973905 bits
I(X,Y): 4.440892098500626e-16 bits


In [111]:
hXY = -np.sum(joint * np.log2(joint + eps))
print(f'H(X,Y): {hXY:.3f} bits')
hX_Y = hXY - hX
print(f'H(X|Y): {hX_Y} bits')
miXY = hX - hX_Y
print(f'I(X,Y): {miXY} bits')

H(X,Y): 6.503 bits
H(X|Y): 3.253156039387617 bits
I(X,Y): -0.00366450219022596 bits


### Summary

print(f'H(X):{entropy(p_x):.4f} bits')
print(f'H(X|Y):{conditional_entropy(p_xy, p_y, b=2):.4f} bits')
print(f'Knowing Y does not change the description of X')
print(f'=> The Mutual Information is 0')